[build]
target = "./index.html"

[watch]
ignore = [
  "./src-tauri",
  "node_modules",
  "./styles.css",
  "./styles/main.css",
  "./package.json",
  "./package-lock.json",
]

[serve]
address = "127.0.0.1"
port = 1420
open = false
